package junit;

import com.syntacticsugar.vooga.authoring.editor.AuthoringEnvironment;
import junit.framework.TestCase;

/**
 * The class <code>AuthoringEnvTest</code> contains tests for the class {@link
 * <code>AuthoringEnvironment</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 11/28/15 12:27 AM
 *
 * @author Henry
 *
 * @version $Revision$
 */
public class AuthoringEnvTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public AuthoringEnvTest(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();
		// Add additional set up code here
	}

	/**
	 * Perform post-test clean up
	 *
	 * @throws Exception
	 *
	 * @see TestCase#tearDown()
	 */
	protected void tearDown() throws Exception {
		super.tearDown();
		// Add additional tear down code here
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = true
 * createTearDown = true
 * createTestFixture = false
 * createTestStubs = true
 * methods = 
 * package = junit
 * package.sourceFolder = voogasalad_SyntacticSugar/src
 * superclassType = junit.framework.TestCase
 * testCase = AuthoringEnvTest
 * testClassType = com.syntacticsugar.vooga.authoring.editor.AuthoringEnvironment
 */