package junit;

import com.syntacticsugar.vooga.authoring.css.CSSWizard;

import javafx.scene.Node;
import javafx.scene.shape.Rectangle;
import junit.framework.TestCase;

/**
 * The class <code>CSSWizardTest</code> contains tests for the class {@link
 * <code>CSSWizard</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 12/3/15 2:17 PM
 *
 * @author Henry Yuen
 *
 * @version $Revision$
 */
public class CSSWizardTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public CSSWizardTest(String name) {
		super(name);
	}

	/**
	 * Run the void tileOpacityOff(Node) method test
	 */
	public void testTileOpacityOff() {
		//fail("Newly generated method - fix or disable");
		// add test code here
		// Temporary Rectangle
		Node testNode = new Rectangle();
		CSSWizard.tileOpacityOff(testNode);
		assertTrue(testNode.getStyleClass().contains("tile-select-off"));
		assertFalse(testNode.getStyleClass().contains("tile-select-on"));
	}

	/**
	 * Run the void tileOpacityOn(Node) method test
	 */
	public void testTileOpacityOn() {
		//fail("Newly generated method - fix or disable");
		// add test code here
		Node testNode = new Rectangle();
		CSSWizard.tileOpacityOn(testNode);
		assertTrue(testNode.getStyleClass().contains("tile-select-on"));
		assertFalse(testNode.getStyleClass().contains("tile-select-off"));
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = true
 * methods = 
 * package = com.syntacticsugar.vooga.authoring.css
 * package.sourceFolder = voogasalad_SyntacticSugar/src
 * superclassType = junit.framework.TestCase
 * testCase = CSSWizardTest
 * testClassType = com.syntacticsugar.vooga.authoring.css.CSSWizard
 */